### ISSUE TITLE
NeedArgs clarification

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#11]
Hey 仕晋,

Does `NeedArgs` means need argument or need option? 

Please see my [demo how to handle none-option parameters](https://github.com/suntong/lang/commit/d995de0507e32ec12525485a7b139ede66fdff69), in which I added a none-option parameters to `build`:

```
Build golang application

Usage:
  gogo build [Options] Arch(i386|amd64)

```

It runs fine:

```
$ gogo build --dir=.. -o out i386
build: {
    "Help": false,
    "Dir": "..",
    "Suffix": ".go,.c,.s",
    "Out": "out"
}
Arch: i386

```

However, my code would panic if the `Arch` none-option parameter is not specified. So we need clarification here. Once again, `rsync` takes an awful lot of options, but besides them, at the end of command line, there are none-option parameters, normally called argument. I hope that `NeedArgs` really means this, which goes with common understanding and all other commands.

Thanks

**Comment by mkideal** [comment]
Ok ,I will fix it.

**Comment by suntong** [comment]
Many thanks!

**Comment by mkideal** [comment]
Hey. I removed `NeedArgs`. Now, `NumArg` added. See commit 0a75f3d and [example_narg_test.go](https://github.com/mkideal/cli/blob/master/example_narg_test.go)

**Comment by suntong** [comment]
That's super! Amazingly thorough!!

**Comment by suntong** [comment]
Please take a look at my 

[allow multiple arguments (none-option parameters) for install](https://github.com/suntong/lang/commit/b540d1be35086741146f773317fd864ddb372236)

I think I've done it right, but this is what I got:

```
$ gogo install pkg1 pkg2 pkg3
ERR! command install pkg1 pkg2 pkg3 not found

```

**Comment by mkideal** [comment]
In this case, you should set `CanSubRoute` true for command `install`, otherwise CLI will try find the command `install`->`pkg1`->`pkg2`->`pkg3`

**Comment by mkideal** [comment]
```go 
var _ = app.Register(&cli.Command{
  	Name: "install",
  	Desc: "Install golang application",
 	Text: "Usage:\n  gogo install [Options] package [package...]",
  	Argv: func() interface{} { return new(installT) },
  	Fn:   install,
 	CanSubRoute: true,
 	NumArg: cli.AtLeast(1),
  })
```

**Comment by suntong** [comment]
Thanks. Works great. 

Hmm.., should `CanSubRoute` true affect `ctx.Path()` as well? 

```go
var _ = app.Register(&cli.Command{
	Name: "install",
	Desc: "Install golang application",
	Text: "Usage:\n  gogo install [Options] package [package...]",
	Argv: func() interface{} { return new(installT) },
	Fn:   install,

	NumArg:      cli.AtLeast(1),
	CanSubRoute: true,
})

...

	ctx.String("%s: %v", ctx.Path(), jsonIndent(argv))

```

```
$ gogo install pkg1 pkg2 pkg3
install pkg1 pkg2 pkg3: {
^^^^^^^^^^^^^^^^^^^^^^
    "Help": false,
    "Dir": "./",
    "Suffix": ".go,.c,.s",
    "Out": ""
}
Installing: [pkg1 pkg2 pkg3]

```

**Comment by mkideal** [comment]
😭，This is a bug!

**Comment by suntong** [comment]
hehe, glad that I can help squashing some. :)

**Comment by mkideal** [comment]
I should write more tests.

**Comment by suntong** [comment]
You "should" have more people to use it. haha...

Don't worry, they will. :)
