### ISSUE TITLE
Global options

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#14]
Hi 仕晋,

I'll enhance my code-gen further before I write the wiki. Meanwhile, another question, 

Does CLI support global options? By "global options" I mean the options supplied before the sub commands. E.g., both `apt-get` and `git` have options before the sub commands:

```
$ apt-get 
apt 1.2.10 (amd64)
Usage: apt-get [options] command
       apt-get [options] install|remove pkg1 [pkg2 ...]
       apt-get [options] source pkg1 [pkg2 ...]
...

$ git 
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
...

```

Any example that shows a sub command has global options and its own "private" options playing together? 

On a very closely related question, when talking about global options, the most common request is for the application configuration, using something like `-C config` to override the defaults. Just like your 017-jsonfile example. My question is, 

Would CLI allow the application to, 

- define those application configuration defaults in the program
- and allow predefined configuration file to override those defaults. Most importantly, the user configuration file can be only a subset of the configurations. For all those not in the user configuration file, take the defaults from definition in the program
- and allow user to use environment var to specify a different configuration file to use
- and allow user to command line (e.g., `-C config`) to specify a different configuration file to use (just like your 017-jsonfile example)

Would CLI allow the above **layered approach**? How much it can do at present? 

Thanks

**Comment by mkideal** [comment]
`Global options` is unsupported at present. I'm trying to think. I will consider every one of your suggestions. I really appreciate you.

**Comment by mkideal** [comment]
Global options is supported now. see exmaple [027-global-option](https://github.com/mkideal/cli/blob/master/_examples/027-global-option/main.go) and commit b9abefb

**Comment by suntong** [comment]
thanks. will try tomorrow.

**Comment by suntong** [comment]
The `1.json` is missing:

`ERR! open 1.json: no such file or directory`

**Comment by suntong** [comment]
ops, sorry, scratch above.

**Comment by suntong** [comment]
PERFECT!! 

Even better that I anticipated. 

Well done. 
Thanks a bunch!
