### ISSUE TITLE
Defaults ignored for root

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#16]
Defaults ignored for root after newest fix. 

Take a look at 
https://github.com/suntong/lang/blob/cli16/lang/Go/src/sys/CLI/027-global-option.go

```
$ go run 027-global-option.go
root
{"Help":false,"Host":"","Port":0}{"Help":false,"Host":"","Port":0}
```

The port default is 80, but output as 0.

**Comment by mkideal** [comment]
```go
Port int    `cli:"p,port" usage:"listening port" dft:80`
```
should be
```go
Port int    `cli:"p,port" usage:"listening port" dft:"80"`
```

**Comment by suntong** [comment]
Ops, I took it for granted that `int` should be without quote, without checking your existing examples. 

My bad, :(
