### ISSUE TITLE
Dealing with regexp in config

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#21]
Hiya, 

How to put regexp in the config?

Please try [your 027-global-option](https://github.com/mkideal/cli/tree/master/_examples/027-global-option) or [mine](https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CLI/027-global-option.go) with the following in the config file:

```json
{
        "host": "regexp\w+test",
        "port": 8080
}
```

That will give an error:

`ERR! invalid character 'w' in string escape code
`

If I escape the `\` like this:

```json
{
        "host": "regexp\\w+test",
        "port": 8080
}
```

the content would be wrong:

```
{"Help":false,"Host":"regexp\\w+test","Port":8080}
                            ^^
```

If I use single quote in the config file, will in turn get:

`ERR! invalid character '\'' looking for beginning of value
`

**Comment by suntong** [comment]
Hmm, maybe escaping the `\` was the answer, 

https://play.golang.org/p/Q4CLOOBV5x

will probe more...

**Comment by suntong** [comment]
Confirmed. 
https://play.golang.org/p/eXZVSit6Bt

Will check why it didn't work for my program. But that's a different story.

**Comment by mkideal** [comment]
First,
```go
`regexp\s+test`
```
equivalent to
```go
"regexp\\s+test"
```

Second,run https://play.golang.org/p/Q4CLOOBV5x and output is
```sh
{"Width":10,"Height":20,"Color":"regexp\\s+test","Open":false}
```

**Comment by suntong** [comment]
I know.

**Comment by suntong** [comment]
I meant that escaping the `\` is the correct answer.
