### ISSUE TITLE
Proper error message for missing argument for parameters

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#23]
When the required argument is missing from the cli parameter, `cli` should point that out, instead of error out on something else:

$ go run 001-hello.go -a
ERR! `` couldn't converted to an uint value

[Normal case shown here](https://github.com/suntong/lang/tree/master/lang/Go/src/sys/CLI#001-hellogo).

**Comment by mkideal** [comment]
Thanks. I have fix it, see commit 7259422

**Comment by suntong** [comment]
Yep. Thx!
