### ISSUE TITLE
Parameter, option & argument

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#24]
May be it is a good idea to standardize the usage of "parameter", "option" & "argument" throughout `cli` according to GNU getopt. 

From `man getopt`:

> The *parameters* are parsed from left to right.  Each _parameter_ is  classified as a short _option_, a long _option_, an _argument_ to an _option_, or a non-option parameter.

I.e., the _parameter_ and _option_ are (almost) interchangeable, while _argument_ normally means the actual value for the _option_. 

I don't know how cohesive such names are used throughout `cli`, but I did notice one that's not quite right -- the output of [003-required-flag.go](https://github.com/suntong/lang/tree/master/lang/Go/src/sys/CLI#003-required-flaggo)

```
$ go run 003-required-flag.go 
ERR! required argument --id missing
```

It is better be called "required _parameter_" instead of _argument_ here. and it might be a good idea to check the whole `cli` messages to check for such cohesive usage (to make 风格更为统一).

**Comment by suntong** [comment]
Here is another one:

>$ go run 001-hello.go -name
ERR! undefined **flag** -n

**Comment by mkideal** [comment]
Thanks for your suggestion. I have fix these error messages.

**Comment by suntong** [comment]
:+1:
