### ISSUE TITLE
Abnormal with root options

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#25]
Hi again 仕晋,

I found two issues with root options (i.e., options not for sub-commands). I've built a small example to show that, https://github.com/suntong/lang/tree/master/lang/Go/src/sys/CLI/015-fileI

- issue 1, `cli.AtLeast(1)` works for sub-commands but not for root options

```
$ go run main.go 
ERR! required argument --name missing
ERR! required argument --tag missing

```

It should show usage instead of complaining. 

- issue 2, self config json not working. 

```
$ cat fi.json 
{ "ID": "1234" }

$ go run main.go -n NN -t TT
{"Help":false,"Name":"NN","Tag":"TT","ID":"","Fi":{}}{"Help":false,"Name":"NN","Tag":"TT","ID":"","Fi":{}}

```

The  "ID" should be "1234" instead of empty, right?

**Comment by mkideal** [comment]
- issue 1: AtLeast not found in command `root. 
	var root = &cli.Command{
		Name: "fi",
		Desc: "File input demo",
		Text: "File input demo with mandatory options",
		Argv: func() interface{} { return new(rootT) },
		Fn:   fi,
	}

- issue 2: Change `Argv: func() interface{} { return new(rootT) }` to `Argv: func() interface{} { argv :=  new(rootT); argv.Self = argv; return argv },`

**Comment by mkideal** [comment]
package main

	import (
		"fmt"
		"github.com/mkideal/cli"
		clix "github.com/mkideal/cli/ext"
		"os"
	)

	type rootT struct {
		cli.Helper
		Self *rootT       `cli:"c,config"usage:"config file" json:"-" parser:"jsonfile" dft:"fi.json"`
		Name string       `cli:"*n,name"usage:"Name (mandatory)"`
		Tag  string       `cli:"*t,tag"usage:"Tag used for record saving (mandatory)"`
		ID   string       `cli:"id"usage:"ID to use"`
		Fi   *clix.Reader `cli:"i,input"usage:"The source (or stdin if unspecified)"`
	}

	var root = &cli.Command{
		NumOption: cli.AtLeast(1),
		Name:      "fi",
		Desc:      "File input demo",
		Text:      "File input demo with mandatory options",
		Argv:      func() interface{} { argv := new(rootT); argv.Self = argv; return argv },
		Fn:        fi,
	}

	func main() {
		cli.SetUsageStyle(cli.ManualStyle) // up-down, for left-right, use NormalStyle
		//NOTE: You can set any writer implements io.Writer
		// default writer is os.Stdout
		if err := cli.Root(root).Run(os.Args[1:]); err != nil {
			fmt.Fprintln(os.Stderr, err)
		}
		fmt.Println("")
	}

	func fi(ctx *cli.Context) error {
		ctx.JSON(ctx.RootArgv())
		ctx.JSON(ctx.Argv())
		fmt.Println()

		return nil
	}

**Comment by suntong** [comment]
Oh, I'm sorry to trouble you with my own silly mistake. You saved my day. Thanks A LOT!
