### ISSUE TITLE
Verbose option

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#26]
Can `cli` provide the *accumulative* option like what ssh does for *verbose*? 

I.e., the more `-v` are specified on the command line, the more verbose it will be. This will be good for other purpose like debug as well. So far my code look like this:

```
       Verbose      int          `cli:"v,verbose"usage:"Be verbose (with level 1 & 2)"`
```

To use it, I have to specify `-v 1` or `-v 2`, a little bit inconvenient than specifying `-v` or `-v -v`. 

Thanks

**Comment by mkideal** [comment]
Ok, but it will take a little bit of time.

**Comment by suntong** [comment]
NP. Just a wish that I might have it some day. No rush.

**Comment by mkideal** [comment]
See commit c86f2c0 and example [030](https://github.com/mkideal/cli/blob/master/_examples/030-counter/main.go)
```go
package main

import (
	"github.com/mkideal/cli"
)

type argT struct {
	cli.Helper
	V cli.Counter `cli:"v" usage:"count verbose"`
}

func main() {
	cli.Run(new(argT), func(ctx *cli.Context) error {
		argv := ctx.Argv().(*argT)
		ctx.String("v=%d\n", argv.V.Value())
		return nil
	})
}
```

```sh
$ go run main.go -v
v=1
$ go run main.go -vv
v=2
$ go run main.go -v -v
v=2
```

**Comment by suntong** [comment]
:+1:
