### ISSUE TITLE
Cloning with HTTPS

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#30]
Hi, 

This is not the first time that I upgrade `cli` package, but today, when I did it, I got:

```
$ go get -v github.com/mkideal/cli
github.com/mkideal/cli (download)
# cd .; git clone https://github.com/mkideal/cli /path/to/Go/src/github.com/mkideal/cli
Cloning into '/path/to/Go/src/github.com/mkideal/cli'...
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
package github.com/mkideal/cli: exit status 128

```

Even git alone with give me errors:

```
cd /path/to/Go/src/github.com/mkideal

$ git clone https://github.com/mkideal/cli
Cloning into 'cli'...
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Do you have any idea why?

**Comment by mkideal** [comment]
tried other pkg?

**Comment by suntong** [comment]
cd /tmp

$ git clone  https://github.com/go-jsonfile/jsonfile
Cloning into 'jsonfile'...
remote: Counting objects: 12, done.
remote: Total 12 (delta 0), reused 0 (delta 0), pack-reused 12
Unpacking objects: 100% (12/12), done.
Checking connectivity... done.

**Comment by mkideal** [comment]
Sorry, I don't known why. Everything is  ok when  I clone it
```bash
git clone https://github.com/mkideal/cli
Cloning into 'cli'...
remote: Counting objects: 1162, done.
remote: Total 1162 (delta 0), reused 0 (delta 0), pack-reused 1162
Receiving objects: 100% (1162/1162), 4.95 MiB | 9.00 KiB/s, done.
Resolving deltas: 100% (696/696), done.
Checking connectivity... done.
```

**Comment by suntong** [comment]
Sorry, my own problem -- I tried it at home just now and worked just fine. 

Will dealt it myself tomorrow. Sorry to have bothered you. 

PS. Some version for my own record:

```
$ apt-cache policy git
git:
  Installed: 1:2.7.4-0ubuntu1
  Candidate: 1:2.7.4-0ubuntu1

$ go version
go version go1.7.1 linux/amd64

```

**Comment by suntong** [comment]
FTA, found the answer at
https://superuser.com/questions/1079126/git-clone-fatal-origin-does-not-appear-to-be-a-git-repository-for-vmware-vmhg
