### ISSUE TITLE
ERR! unexpected end after 36

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#33]
Hi there, 

Please take a look at the code
https://gist.github.com/suntong/7eed1480ce3e7f508b4d728547696a33

Here is what happens when I run it:

```
$ go run /tmp/picv.go
ERR! unexpected end after 36
```

I found that it all comes down to the "$" sign at 
https://gist.github.com/suntong/7eed1480ce3e7f508b4d728547696a33#file-picv-go-L21

removing it and the program works fine. 

Looks like a bug, is it? Thx

**Comment by mkideal** [comment]
`dft:".*\\.jpg$"` should be changed to `dft:".*\\.jpg$$"` because `$` is a special character!

**Comment by suntong** [comment]
Gotya. thx.
