### ISSUE TITLE
How to add default flag for jsonfile?

### ISSUE THREAD

**Issue by nerdneilsfield** [mkideal/cli#36]
I try to use this one:

```
JSON config `cli:"c,config" usage:"parse json from file" parser:"jsonfile" dft: "config.json"`

```

**Comment by suntong** [comment]
Is 

https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CLI/027-global-option.go#L21

what you were looking for?

**Comment by nerdneilsfield** [comment]
I'll try...

谢谢

**Comment by suntong** [comment]
That's the final answer. Closing it now and feel free to reopen if you have any more questions.
