### ISSUE TITLE
Simplify access to nested args

### ISSUE THREAD

**Issue by oakad** [mkideal/cli#38]
In an app with nested sub-commands, it may be necessary to look at the intermediate command's args. Currently, this is only achievable via `GetArgvList` method, which is unnecessarily complicated if one only wants to look at the args of the immediate sub-command parent.

An addition of `ArgvAt(pos int)` method to `Context` object, with the obvious semantics of `return ctx.argvList[pos]`, (or something similar in intent) will be most welcome.

**Comment by suntong** [comment]
Please take a look at #46 -- would you like to submit a PR?

**Comment by suntong** [comment]
Only close after the doc has been updated as well?

**Comment by mkideal** [comment]
doc added.
