### ISSUE TITLE
Publish new release please

### ISSUE THREAD

**Issue by chapsuk** [mkideal/cli#39]
Thanks!

**Comment by suntong** [comment]
Hi @chapsuk, the https://github.com/mkideal/cli/ _is_ the latest code. what do you mean by "publish new release"? what features were you expecting that are not seen here?

**Comment by chapsuk** [comment]
Hi, i mean `github` releases https://github.com/mkideal/cli/releases. 
They are convenient to use for vendoring. Thanks!

**Comment by suntong** [comment]
Oh, thx for explanation.

**Comment by suntong** [comment]
Please take a look at #46.
