### ISSUE TITLE
Self config allows to go with the executable file

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#40]
- One niche `cli` has is to define a self-config .json file that allows using the .json file to control the executable file behavior. 
- Such self-config .json files almost always go with the executable file
- However if we put such executable somewhere in the path,  `cli` currently ready such self-config .json file from `pwd`, and would fail if it is not:

Using 
https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CLI/027-global-option.go#L21
to showcase the situation:

```sh
.../lang/Go/src/sys/CLI$ 027-global-option
root
{"Host":"regexp\\s+test","Port":8080}{"Host":"regexp\\s+test","Port":8080}
[2 15]

cd ../

.../lang/Go/src/sys$ CLI/027-global-option
ERR! open 027-global-option.json: no such file or directory
```

If we allow such self-config .json files to reside where the executable file is, then such with-self-config executable can truly be invoked from everywhere.

**Comment by suntong** [comment]
Same test as above, 

```sh
.../lang/Go/src/sys/CLI$ 027-global-option
root
{"Host":"regexp\\s+test","Port":8080}{"Host":"regexp\\s+test","Port":8080}
[2 15]

cd ../

.../lang/Go/src/sys$ CLI/027-global-option
root
{"Host":"regexp\\s+test","Port":8080}{"Host":"regexp\\s+test","Port":8080}
[2 15]
```

I.e. problem fixed -- such with-self-config executable can truly be invoked from everywhere now.

**Comment by mkideal** [comment]
It's not a good idea for changing `ReadJSONFromFile` method.

**Comment by mkideal** [comment]
> os.Args[0] will be an empty string when the program is invoked from within the path

**Comment by suntong** [comment]
- Build https://github.com/suntong/lang/blob/master/lang/Go/src/sys/CLI/027-global-option.go as-is, using `"github.com/go-easygen/cli"`.
- Run from parent dir. E.g., `.../lang/Go/src/sys$ CLI/027-global-option`, as shown above. 
- Copy the executable and .json file to somewhere within the PATH
- Invoke it without specifying any path, so the program will be invoked from within the path
- Now try to modify it with the latest `github.com/mkideal/cli` and redo above steps again.

**Comment by mkideal** [comment]
I have tried it. but `os.Args[0]` is not empty, `filepath.Dir(os.Args[0])` is `.`
