### ISSUE TITLE
When decoding Time with empty string, toggle IsSet

### ISSUE THREAD

**Issue by rtgibbons** [mkideal/cli#55]
https://github.com/mkideal/cli/blob/205c0b83093311fee1b048df54ae7d7b77dd0ef2/ext/decoders.go#L51-L55

I think it makes sense to toggle IsSet to true here?

**Comment by suntong** [comment]
close via https://github.com/mkideal/cli/commit/238c6b9d5b144e972cef28b7129ca7eebdecbf03
