### ISSUE TITLE
Printing self help

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#57]
Hi @mkideal, 

Given a program, say https://github.com/mkideal/cli/blob/master/_examples/002-flag/main.go, if I want to do further logical process of the parameters, how do I print a self help if the given parameter is invalid. 

Again, using https://github.com/mkideal/cli/blob/master/_examples/002-flag/main.go as the example, how to do:

```go
 if argv.Port < 1024 { print self help }
```

where the self help is the output running the program with `-h`:

```
Options:

  -h, --help     display help information
  -p, --port     short and long format flags both are supported
  -x             boolean type
  -y             boolean type, too
```

thx!

**Comment by suntong** [comment]
Same question when-using/for child-command: https://github.com/mkideal/cli#example-8-child-command

**Comment by mkideal** [comment]
You can print help message directly:

```
if argv.Port < 1024 {
    ctx.String("Print yourself help information\n")
}
```

**Comment by suntong** [comment]
yeah, but I want to print a self help, 
_"**where the self help is the output running the program with `-h`"**_

not construction again myself.

**Comment by mkideal** [comment]
if argv.Port < 1024 {
    ctx.WriteUsage()
}

**Comment by suntong** [comment]
Oh, 

Thought it was https://godoc.org/github.com/mkideal/cli#Context.Usage, but it's actually https://godoc.org/github.com/mkideal/cli#Context.WriteUsage

Thanks
