### ISSUE TITLE
Command alias

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#58]
Is there a way to register/provide shorter alias names to command, like `npm i` stands for `npm install`?

**Comment by mkideal** [comment]
Use `Aliases` as following

```
Command{
    Name: "remove",
    Aliases: []string{"rm"},
    Fn: doSomething,
}
```

**Comment by suntong** [comment]
Thanks @mkideal 

```
Commands:

  help    display help information
  child   this is a child command(aliases cd,cld)
```

There is better a space before the "`(`". OK I send in PR for it?

**Comment by mkideal** [comment]
OK.

**Comment by suntong** [comment]
Thanks. Done.
