### ISSUE TITLE
IsSet always returns false

### ISSUE THREAD

**Issue by chrjen** [mkideal/cli#62]
v0.2.7, although using previous versions didn't seem to help.

I'm trying to figure out if a flag is present or not as I only want to use the value if it was specified. I tried using `IsSet` though it doesn't seem to work. Example program,

```golang
package main

import (
	"fmt"
	"os"

	"github.com/mkideal/cli"
	clix "github.com/mkideal/cli/ext"
)

type argT struct {
	Name string    `cli:"name" usage:"read name"`
	Time clix.Time `cli:"time" usage:"read text"`
}

func main() {
	os.Exit(cli.Run(new(argT), func(ctx *cli.Context) error {
		argv := ctx.Argv().(*argT)

		fmt.Println(ctx.IsSet("name"), ctx.IsSet("time"))
		fmt.Println(argv.Name, argv.Time)

		return nil
	}))
}
```

**Output:**
```bash
% ./cli
false false
 0001-01-01 00:00:00 +0000 UTC
% ./cli maing.go --name Frank --time 2021-08-10
false false
Frank 2021-08-10 00:00:00 +0000 UTC
```

Shouldn't `IsSet` return true here? The problem seems to be because `ctx.flagSet.flagMap` is always empty.

**Comment by mkideal** [comment]
Preappend double ‘-‘ to long flag name, one ‘-‘ to short flag name, e.g.

ctx.IsSet(“—name”)
ctx.IsSet(“-v”)
