### ISSUE TITLE
cli packge broken

### ISSUE THREAD

**Issue by suntong** [mkideal/cli#73]
I'm using `github.com/mkideal/cli` in https://github.com/suntong/html2md/blob/master/html2md_main.go, and now it is broken, due to `mkideal/expr` gone or the `pkg` repository has been archived:

```
. . .
Cloning into '/home/runner/go/src/github.com/mkideal/expr'...
fatal: could not read Username for 'https://github.com/': terminal prompts disabled
package github.com/mkideal/expr: exit status 128
. . .
golang.org/x/term (download)
github.com/mkideal/pkg (download)
Error: Process completed with exit code 1.
```

**Comment by mkideal** [comment]
I'm so sorry for my mistake! Now, everything is ok.
